# Generated by Django 5.1.2 on 2024-11-02 17:17

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=django_quill.fields.QuillField(),
        ),
    ]
