# Generated by Django 4.2.17 on 2026-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_ingredients_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="dietary_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated dietary tags from ingredient analysis",
            ),
        ),
    ]
