name: Deploy Recipe App to Amazon Linux EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to Amazon Linux EC2
      env:
        DEPLOY_DIR: "/home/ec2-user/Recipe-sharing-application"
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
        # Navigate to the deployment directory
        cd $DEPLOY_DIR || exit 1

        # Pull the latest code
        git pull origin main

        # Set up Python virtual environment
        if [ ! -d .venv ]; then
          python3 -m venv .venv
        fi
        source .venv/bin/activate

        # Install project dependencies
        pip install --upgrade pip
        pip install -r requirements.txt

        # Run migrations and collect static files
        python manage.py migrate
        python manage.py collectstatic --noinput

        # Restart Gunicorn service
        sudo systemctl restart gunicorn
        "

